[package]
name = "r-unic/service-event-linker"
description = "Link events from services to an object."
version = "0.1.0"
license = "MIT"
authors = ["Runic"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
janitor = "howmanysmall/janitor@1.15.6"